//-----------------------------Suppliers-----------------------

http://127.0.0.1:3002/api/supplier/registerSupplier

http://127.0.0.1:3002/api/supplier/getSuppliers

http://127.0.0.1:3002/api/supplier/getSupplier/:id

http://127.0.0.1:3002/api/supplier/modifySupplier/:id

//-----------------------------------------------------

//--------------------Órdenes de Compra de Productos-------------

http://127.0.0.1:3002/api/purchaseOrder/registerPurchaseOrder

http://127.0.0.1:3002/api/purchaseOrder/getPurchaseOrders

http://127.0.0.1:3002/api/purchaseOrder/getPuchaseOrder/:id

http://127.0.0.1:3002/api/purchaseOrder/modifyPurchaseOrder/:id